import type { HeroPersonalItem } from "@/lib/types";

export const hero = {
  greeting: "Hi, I'm 南口遼河.",
  lineTwoPrefix: "課題を",
  highlight: "構造化",
  lineThree: "し、価値に変える。",
  subtitle:
    "課題を構造的に分析し、人や技術を巻き込みながら改善を実装するエンジニアです。ベトナムでのインターンでは複数AIエージェントによる開発支援システムを、ハッカソンでは「AIの弱点をコンテンツ化する」アイデアで努力賞を受賞しました。",
  ctaLabel: "view my works",
  ctaHref: "#works",
  personalWindowFilename: "profile.json",
  personalHint: "各行にカーソルを合わせる(タップ)と写真が変わります",
  personalItems: [
    { text: "const me = {", tone: "default" },
    {
      text: "  smile: '満面の笑み',",
      tone: "muted",
      photo: "/images/hero/profile-smile.jpg",
      caption: "南口遼河",
      focus: "50% 30%",
    },
    {
      text: "  igo: '囲碁に熱中する',",
      tone: "muted",
      photo: "/images/hero/profile-go.jpg",
      caption: "囲碁を楽しむ様子",
      focus: "35% 15%",
    },
    {
      text: "  birthday: 'ヤドン推しの誕生日会',",
      tone: "muted",
      photo: "/images/hero/profile-birthday.jpg",
      caption: "誕生日をお祝い",
      focus: "20% 20%",
    },
    {
      text: "  cosplay: 'オオカミに変身',",
      tone: "muted",
      photo: "/images/hero/profile-wolf-cosplay.jpg",
      caption: "コスプレを楽しむ一面",
      focus: "60% 30%",
    },
    {
      text: "  santa: '仮装イベントに参戦',",
      tone: "muted",
      photo: "/images/hero/profile-santa.jpg",
      caption: "仮装イベントにて",
      focus: "75% 25%",
    },
    {
      text: "  izakaya: '友人としっぽり',",
      tone: "muted",
      photo: "/images/hero/profile-drinks.jpg",
      caption: "友人との食事にて",
      focus: "55% 15%",
    },
    {
      text: "  fittingRoom: '試着室にて',",
      tone: "muted",
      photo: "/images/hero/profile-fitting-room.jpg",
      caption: "買い物中の一コマ",
      focus: "45% 8%",
    },
    {
      text: "  snapshot: '何気ない日常',",
      tone: "muted",
      photo: "/images/hero/profile-candid.jpg",
      caption: "何気ない日常のひとこま",
      focus: "45% 15%",
    },
    { text: "};", tone: "default" },
    { text: "", tone: "default" },
    { text: "const hobbies = [", tone: "default" },
    {
      text: "  'ダーツ',",
      tone: "success",
      photo: "/images/hero/hobby-darts.jpg",
      caption: "趣味: ダーツ",
    },
    {
      text: "  'ビリヤード',",
      tone: "success",
      photo: "/images/hero/hobby-billiards.jpg",
      caption: "趣味: ビリヤード",
    },
    {
      text: "  'ボードゲーム',",
      tone: "success",
      photo: "/images/hero/hobby-boardgame.jpg",
      caption: "趣味: ボードゲーム",
    },
    {
      text: "  '手料理',",
      tone: "success",
      photo: "/images/hero/hobby-cooking.jpg",
      caption: "趣味: 手料理",
    },
    {
      text: "  '海外旅行(ホイアン)',",
      tone: "success",
      photo: "/images/hero/hobby-travel-hoian.jpg",
      caption: "海外旅行(ベトナム・ホイアン)",
      focus: "50% 70%",
    },
    {
      text: "  '海外旅行(空の上)',",
      tone: "success",
      photo: "/images/hero/hobby-travel-flight.jpg",
      caption: "海外旅行の道中にて",
      focus: "50% 35%",
    },
    {
      text: "  '葉巻',",
      tone: "success",
      photo: "/images/hero/hobby-cigar.jpg",
      caption: "趣味: 葉巻",
      focus: "40% 55%",
    },
    {
      text: "  '友人との乾杯',",
      tone: "success",
      photo: "/images/hero/hobby-cheers.jpg",
      caption: "趣味: 友人との時間",
    },
    { text: "];", tone: "default" },
  ] satisfies HeroPersonalItem[],
};
