import type { SkillItem } from "@/lib/types";

export const skills = {
  title: "Tech Stack",
  subtitle: "設計・実装・運用に使用している技術とツールの一覧です。",
  detailHint: "経験年数・レベルは仮の値です。実際の内容に差し替えてください。",
  items: [
    {
      name: "TypeScript",
      icon: "/images/icons/skills/skill_icon_typescript.svg",
      years: "1年(仮)",
      level: 3,
      description: "(仮)Next.jsアプリのフロントエンド実装で日常的に使用。型設計を意識したコンポーネント設計ができる。",
    },
    {
      name: "React",
      icon: "/images/icons/skills/skill_icon_react.svg",
      years: "1年(仮)",
      level: 3,
      description: "(仮)複数のハッカソン・個人開発でUI実装に使用。状態管理・コンポーネント分割の基本を理解している。",
    },
    {
      name: "Next.js",
      icon: "/images/icons/skills/skill_icon_nextjs.svg",
      years: "1年(仮)",
      level: 3,
      description: "(仮)本ポートフォリオサイトを含む複数プロジェクトで採用。App Routerでのページ・API実装ができる。",
    },
    {
      name: "Python",
      icon: "/images/icons/skills/skill_icon_python.svg",
      years: "2年(仮)",
      level: 4,
      description: "(仮)AIエージェント開発・バックエンド実装で中心的に使用。LangChain/LangGraphを用いた開発経験あり。",
    },
    {
      name: "FastAPI",
      icon: "/images/icons/skills/skill_icon_fastapi.svg",
      years: "半年(仮)",
      level: 2,
      description: "(仮)チーム開発でバックエンドAPIの実装を担当した経験あり。基本的なCRUD APIを構築できる。",
    },
    {
      name: "Tailwind CSS",
      icon: "/images/icons/skills/skill_icon_tailwind.svg",
      years: "1年(仮)",
      level: 3,
      description: "(仮)本サイトを含むフロントエンド実装で使用。デザインシステムに沿ったスタイリングができる。",
    },
    {
      name: "PostgreSQL",
      icon: "/images/icons/skills/skill_icon_postgresql.svg",
      years: "半年(仮)",
      level: 2,
      description: "(仮)個人開発・チーム開発でデータベース設計から基本的なクエリ実装まで対応した経験あり。",
    },
    {
      name: "Docker",
      icon: "/images/icons/skills/skill_icon_docker.svg",
      years: "1年(仮)",
      level: 2,
      description: "(仮)開発環境・AIエージェントシステムのコンテナ化に使用。Dockerfile/docker-composeの基本操作ができる。",
    },
    {
      name: "Git",
      icon: "/images/icons/skills/skill_icon_git.svg",
      years: "2年(仮)",
      level: 4,
      description: "(仮)個人開発・チーム開発の両方で日常的に使用。ブランチ運用やPRベースの開発フローに慣れている。",
    },
  ] satisfies SkillItem[],
  otherLabel: "Other Tools & Technologies",
  otherTools: [
    "JavaScript",
    "Go",
    "HTML / CSS",
    "LangChain",
    "LangGraph",
    "OpenAI API",
    "Google Gemini API",
    "Flask",
    "SQLite",
    "Vite",
    "shadcn/ui",
    "Vercel",
    "Railway",
    "Hugging Face Spaces",
    "GitHub",
    "Claude Code",
  ],
};
